#!/usr/bin/env python3
"""Build the ADP API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {

}

LINES = [
    {
        "name": 'ADP Platform',
        "color": '#D52B1E',
        "closed": True,
        "stations": [
        ('Workers', (640, 260)),
        ('Payroll', (840, 460)),
        ('Embedded Payroll', (640, 660)),
        ('Benefits', (440, 460)),
        ],
    },
]

URL_OVERRIDES = {
    'Workers': 'https://apis.apis.io/apis/adp/adp-workers-api/',
    'Payroll': 'https://apis.apis.io/apis/adp/adp-payroll-api/',
    'Embedded Payroll': 'https://apis.apis.io/apis/adp/adp-embedded-payroll-api/',
    'Benefits': 'https://apis.apis.io/apis/adp/adp-benefits-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The ADP API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: adp/openapi · github.com/api-evangelist/adp',
        out_dir=Path(__file__).resolve().parent,
        out_basename='adp-subway-map',
        provider_id='adp',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
